export const navigations = {
  LOGIN: "login",
  BOTTOM_NAVIGATION: "bottomNavigation",
  HOME_ROUTE: "homeRoute",
  MAP_ROUTE: "mapRoute",
  HOMESCREEN: "home",
  EVENT_ROUTE: "eventRoute",
  EVENTSCREEN: "event",
  CALENDAR: "calendar",
  CHAT: "chat",
  MAP: "map",
  EVENT_DETAIL: "eventDetail",
  PROFILE: "profile",
  ADMIN_TOOLS: "adminTools",
  CHECK_IN: "checkIn",
  PAYMENT: "payment",
  GENERIC_WEB_VIEW: "webView",
  SIGNUP: "signUp",
  CREATE_POST: "createPost",
  EDIT_POST: "editPost",
  CREATE_EDIT_POST_GRATIS: "createEditPostGratis",
  RECENTUSERPROFILE: "recentUserProfile",
  COMMENTLIST: "commentList",
  ADDPAYOUTEXPENSE: "addPayoutExpense",
  EDITPAYOUTEXPENSE: "editPayoutExpense",
  EDIT_OFFER: "editPostOffer",
  EDIT_REQUEST: "editPostRequest",
  EDITPOSTGRATIS: "createEditPostGratis",
};

export const bottomNavigationVisibleScreens = [
  navigations.HOMESCREEN,
  navigations.EVENTSCREEN,
  navigations.CHAT,
  navigations.MAP,
  navigations.CALENDAR,
];
