source "https://rubygems.org"

gem "fastlane"
gem "screengrab"

# To Resolve warnings about libraries removed in Ruby 3.4.0
gem "mutex_m"
gem "abbrev"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
