export const stringsAndLabels = {
  mobileOrEmail: 'Mobile number of Email',
  password: 'Password',
  iAgree: 'I agree to the',
  tnc: 'terms and conditions',
  login: 'Log in',
  forgotPassword: 'Forgot password',
  loginGoogle: 'Login/Register with Google',
  aboutEvent: 'About Event',
  buyTicket: 'Buy Ticket',
  ticketCheckout: 'Ticket Checkout',
  purchase: 'Purchase',
  comingSoon: 'Coming Soon',
  event: 'Event',
  offer: 'Offer',
  request: 'Request',
  gratitude: 'Gratitude',
  stripePayout: 'Add Stripe for Payout',
  about: 'About',
  myEvents: 'My Events',
  activity: 'Activity',
  membership: 'Membership',
  player: 'Player',
  eventProducer: 'Event Producer',
  aboutMe: 'About Me',
  skills: 'Skills',
  addSkill: 'Add a skill',
  membershipCheckout: 'Membership Checkout',
  productMerchant: 'Product Merchant',
  billedMonthly: 'Billed Monthly',
  billedYearly: 'Billed Yearly',
  adminTools: 'Admin Tools',
  checkIns: 'Check Ins',
  tickets: 'Tickets',
  confirmationEmail: 'Confirmation Email',
  attendees: 'Attendees',
  enterTitle: 'Enter Title',
  enterAddress: 'Enter Address',
  enterVenue: 'Enter Venue',
  enterEmail: 'Enter Email',
  ticketEdit: 'Ticket Edit',
  ticketName: 'Ticket Name',
  ticketTimeframe: 'Ticket Timeframe',
  ticketPrice: 'Ticket Price',
  save: 'Save',
  selectStartDate: 'Select Start Date',
  selectEndDate: 'Select End Date',
  to: 'to',
  ticketholderCheckin: 'Ticketholder Checkin',
  checkIn: 'Check In',
  checkedIn: 'Checked In',
  logout: 'Log out',
  areYouLogout: 'Are you sure you want to log out?',
  yes: 'Yes',
  no: 'No',
  noDataText: 'No More Data Found',
  noEventsFound: 'No Events Found',
  producer: 'Producer',
  selectStartTime: 'Select Start Time',
  selectEndTime: 'Select End Time',
  pleaseEdit: 'Please edit something',
  updateAvailable:
    'App update is available. Please update the app from app store.',
  updateApp: 'Update App',
  noTicketsAvailable: 'No tickets available to purchase',
  noCheckedInUserFound: 'No checked-in user found',
  purchaseSubscription: 'Please purchase the subscription',
  linkCopied: 'Link copied to clipboard',
  noAttendees: 'No Attendees Found',
  enterAboutEvent: 'Enter About Event',
};
