export const stringsAndLabels = {
  mobileOrEmail: "Email",
  password: "Password",
  iAgree:
    "Your data is safe with ONE|Local. By clicking the “sign up” button above, you agree to the  ",
  tnc: "terms, policy, & EULA",
  login: "Log in",
  forgotPassword: "Forgot password",
  loginGoogle: "Google Sign On",
  loginApple: "Apple Sign On",
  aboutEvent: "About Event",
  buyTicket: "Buy Ticket",
  ticketCheckout: "Ticket Checkout",
  purchase: "Purchase",
  comingSoon: "Coming Soon",
  event: "Event",
  offer: "Offer",
  request: "Request",
  gratitude: "Gratitude",
  stripePayout: "Add Stripe for Payout",
  about: "About",
  myEvents: "My Events",
  activity: "Activity",
  membership: "Membership",
  player: "Player",
  eventProducer: "Event Producer",
  aboutMe: "About Me",
  skills: "Skills",
  addSkill: "Add a skill",
  membershipCheckout: "Membership Checkout",
  productMerchant: "Product Merchant",
  billedMonthly: "Billed Monthly",
  billedYearly: "Billed Yearly",
  adminTools: "Admin Tools",
  checkIns: "Check Ins",
  tickets: "Tickets",
  confirmationEmail: "Confirmation Email",
  attendees: "Attendees",
  enterTitle: "Enter Title",
  enterAddress: "Enter Address",
  enterVenue: "Enter Venue",
  enterEmail: "Enter Email",
  ticketEdit: "Ticket Edit",
  ticketAdd: "Ticket Create",
  ticketName: "Ticket Name",
  ticketTimeframe: "Ticket Timeframe",
  ticketPrice: "Ticket Price",
  save: "Save",
  selectStartDate: "Select Start Date",
  selectEndDate: "Select End Date",
  to: "to",
  ticketholderCheckin: "Ticketholder Checkin",
  checkIn: "Check In",
  checkedIn: "Checked In",
  logout: "Log out",
  areYouLogout: "Are you sure you want to log out?",
  yes: "Yes",
  no: "No",
  deletePost: "Are you sure you want to delete this post ?",
  noDataText: "No More Data Found",
  noEventsFound: "No Events Found",
  noPostFound: "No Post Found",
  producer: "Producer",
  selectStartTime: "Select Start Time",
  selectEndTime: "Select End Time",
  pleaseEdit: "Please edit something",
  updateAvailable:
    "App update is available. Please update the app from app store.",
  updateApp: "Update App",
  noTicketsAvailable: "No tickets available to purchase",
  noCheckedInUserFound: "No checked-in user found",
  nocommentFound: "No Comment Data Found",
  purchaseSubscription: "Please purchase the subscription",
  linkCopied: "Link copied to clipboard",
  noAttendees: "No Attendees Found",
  enterAboutEvent: "Enter About Event",
  explorerLbl: "Explorer",
  orgOperator: "Org Operator",
  serviceProvider: "Service Provider",
  playerMembership: "Player Membership",
  eventProvider: "Event Producer",
  playerDesc:
    "By signing up as a Player, you get ONE|Pass, which grants you 10% discounts at participating local businesses.  You also get to post offers and requests on the main feed.",
  eventProDesc:
    "By signing up as an Event Producer you can create events, invite users, and sell tickets. You also get the perks of a Player membership to get discounts at local businesses, and post offers and requests on the main feed.",
  serviceDesc:
    "By signing up as a Provider you can list and offer your skills as Services. You also get the perks of a Player membership to get discounts at local businesses, and post offers and requests on the main feed.",
  orgOpDesc:
    "By signing up as an Operator you can create organizations, and engage with Players as a business. If you sign up as a ONE Pass business (offing players 10% off at your business), you can waive the monthly fee!. You also get the perks of a Player membership to post offers and requests on the main feed.",
  signUp: "Sign Up!",
  playerText: "You are currently signed up as a player!",
  cancleSubscription: "cancel subscription",
  membershipInfo:
    "By signing up as a Player, you get ONE|Pass, which grants you 10% discounts at participating local businesses. You also get to post offers and requests on the main feed.",
  addCard: "+ Add Card",
  addCardTwo: "ADD CARD",
  cancle: "Cancel",
  paymentinfo: "Payment Information",
  exp: "Exp.",
  addCardOne: "Add Card",
  cardinfo: "Card Info",
  dot: ".",
  slash: "/",
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  phoneNo: "Mobile Number",
  confirmPass: "Confirm Password",
  signUpTwo: "Sign Up",
  updateQuestion: "Update Questions",
  queAnsTitle: "Update your Profile Questions!",
  quantity: "No of Quantity",
  pricetax: "Price and Taxes",
  totalAmount: "Total Amount to Pay    ",
  postOffer: "Post Offer",
  deleteAccount: "Delete Account",
  areYouDeleteAccount: "Are you sure you want to Delete Account?",
  blockUser: "Block User",
  deletePostTitle: "Delete Post",
  areYouBlockUser:
    "If you Block this user you are not able to see any post from this user.",
  hidePost: "Hide Content",
  areyouHide: "Are you sure you want to hide this Post?",
  reportUser: "Report User",
  areyouReport: "Report this user Reason",
  catchphrase: "Catchphrase",
  nickname: "Nick Name",
  birthday: "Birth Day",
  state: "State",
  city: "City",
  profilepic: "Profile Picture",
  bgImage: "Background Picture",
  cancleEvent: "Cancle Event",
  subTotal: "Subtotal",
  serviceFee: "Service Fee",
  salesTax: "Sales Tax",
  total: "Total",
  pay: "PAY",
  billingAdd: "Billing address *",
  platformFee: "Platform Fee",
  paymentFee: "Payment Fee",
  eventDes: "You need to sign up as an Event Producer to create Events.",
};
